enum API_RESPONSE_CODE {
    // Auth - Signup/Login/Logout
    USER_CREATED = "USER_CREATED",
    EMAIL_VERIFICATION_SENT = "EMAIL_VERIFICATION_SENT",
    EMAIL_VERIFIED = "EMAIL_VERIFIED",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED",
    PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS",
    GOOGLE_ACCOUNT_EXISTS = "GOOGLE_ACCOUNT_EXISTS",

    // Errors - Auth
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT",
    INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_INVALID = "TOKEN_INVALID",

    // Validation
    VALIDATION_ERROR = "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
    INVALID_FIELD_FORMAT = "INVALID_FIELD_FORMAT",

    // General Errors
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    FORBIDDEN = "FORBIDDEN",
    UNAUTHORIZED = "UNAUTHORIZED",
    NOT_FOUND = "NOT_FOUND",
    BAD_REQUEST = "BAD_REQUEST",
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

    // General Success
    DATA_FETCHED = "DATA_FETCHED",
    DATA_UPDATED = "DATA_UPDATED",
    DATA_DELETED = "DATA_DELETED",
    DATA_CREATED = "DATA_CREATED",
}

export default API_RESPONSE_CODE;
