/*
  Warnings:

  - The values [HOUSE,FOOD,ENTERTAINMENT,TRANSPORT,UTILITIES,LIFE] on the enum `ExpenseType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ExpenseType_new" AS ENUM ('HOUSE_ELECTRONICS', 'HOUSE_FORNITURE', 'HOUSE_MAINTENANCE', 'HOUSE_MORTGAGE', 'HOUSE_OTHER', 'HOUSE_PETS', 'HOUSE_RENT', 'HOUSE_SERVICES', 'HOUSE_SUPPLIES', 'FOOD_DRINKS', 'FOOD_FOOD', 'FOOD_OTHER', 'FOOD_UTENSILS', 'ENTERTAINMENT_GAMES', 'ENTERTAINMENT_MOVIES', 'ENTERTAINMENT_MUSIC', 'ENTERTAINMENT_OTHER', 'ENTERTAINMENT_SPORTS', 'UNCATEGORIZED', 'TRANSPORT_BUS', 'TRANSPORT_CAR', 'TRANSPORT_FUEL', 'TRANSPORT_HOTEL', 'TRANSPORT_OTHER', 'TRANSPORT_PARKING', 'TRANSPORT_PLANE', 'TRANSPORT_TAXI', 'TRANSPORT_TRAIN', 'UTILITIES_CLEANING', 'UTILITIES_HEATING', 'UTILITIES_LIGHT', 'UTILITIES_OTHER', 'UTILITIES_PHONE', 'UTILITIES_TRASH', 'UTILITIES_TV', 'UTILITIES_WATTER', 'UTILITIES_WIFI', 'LIFE_CLOTHES', 'LIFE_DOCTORS', 'LIFE_GIFTS', 'LIFE_INSURANCES', 'LIFE_NURSERY', 'LIFE_OTHER', 'LIFE_TAXES', 'LIFE_UNIVERSITY');
ALTER TABLE "Expense" ALTER COLUMN "type" TYPE "ExpenseType_new" USING ("type"::text::"ExpenseType_new");
ALTER TYPE "ExpenseType" RENAME TO "ExpenseType_old";
ALTER TYPE "ExpenseType_new" RENAME TO "ExpenseType";
DROP TYPE "ExpenseType_old";
COMMIT;
