import {
    Armchair,
    Baby,
    Beer,
    Bike,
    BriefcaseMedical,
    BrushCleaning,
    BusFront,
    Calculator,
    CarFront,
    CarTaxiFront,
    CircleParking,
    Container,
    CookingPot,
    Droplet,
    Fuel,
    Gamepad2,
    Gift,
    GraduationCap,
    Hamburger,
    Hammer,
    HandPlatter,
    Heater,
    Hotel,
    House,
    HousePlus,
    Lightbulb,
    Music,
    NotebookPen,
    PawPrint,
    Phone,
    Plane,
    Popcorn,
    Receipt,
    Shell,
    ShieldCheck,
    Shirt,
    Tickets,
    TrainFront,
    Trash2,
    Tv,
    Utensils,
    Volleyball,
    Wifi,
    Zap,
} from "lucide-react";

export enum EXPENSE_TYPE {
    HOUSE_ELECTRONICS = "HOUSE_ELECTRONICS",
    HOUSE_FORNITURE = "HOUSE_FORNITURE",
    HOUSE_MAINTENANCE = "HOUSE_MAINTENANCE",
    HOUSE_MORTGAGE = "HOUSE_MORTGAGE",
    HOUSE_OTHER = "HOUSE_OTHER",
    HOUSE_PETS = "HOUSE_PETS",
    HOUSE_RENT = "HOUSE_RENT",
    HOUSE_SERVICES = "HOUSE_SERVICES",
    HOUSE_SUPPLIES = "HOUSE_SUPPLIES",

    FOOD_DRINKS = "FOOD_DRINKS",
    FOOD_FOOD = "FOOD_FOOD",
    FOOD_OTHER = "FOOD_OTHER",
    FOOD_UTENSILS = "FOOD_UTENSILS",

    ENTERTAINMENT_GAMES = "ENTERTAINMENT_GAMES",
    ENTERTAINMENT_MOVIES = "ENTERTAINMENT_MOVIES",
    ENTERTAINMENT_MUSIC = "ENTERTAINMENT_MUSIC",
    ENTERTAINMENT_OTHER = "ENTERTAINMENT_OTHER",
    ENTERTAINMENT_SPORTS = "ENTERTAINMENT_SPORTS",

    UNCATEGORIZED = "UNCATEGORIZED",

    TRANSPORT_BUS = "TRANSPORT_BUS",
    TRANSPORT_CAR = "TRANSPORT_CAR",
    TRANSPORT_FUEL = "TRANSPORT_FUEL",
    TRANSPORT_HOTEL = "TRANSPORT_HOTEL",
    TRANSPORT_OTHER = "TRANSPORT_OTHER",
    TRANSPORT_PARKING = "TRANSPORT_PARKING",
    TRANSPORT_PLANE = "TRANSPORT_PLANE",
    TRANSPORT_TAXI = "TRANSPORT_TAXI",
    TRANSPORT_TRAIN = "TRANSPORT_TRAIN",

    UTILITIES_CLEANING = "UTILITIES_CLEANING",
    UTILITIES_HEATING = "UTILITIES_HEATING",
    UTILITIES_LIGHT = "UTILITIES_LIGHT",
    UTILITIES_OTHER = "UTILITIES_OTHER",
    UTILITIES_PHONE = "UTILITIES_PHONE",
    UTILITIES_TRASH = "UTILITIES_TRASH",
    UTILITIES_TV = "UTILITIES_TV",
    UTILITIES_WATTER = "UTILITIES_WATTER",
    UTILITIES_WIFI = "UTILITIES_WIFI",

    LIFE_CLOTHES = "LIFE_CLOTHES",
    LIFE_DOCTORS = "LIFE_DOCTORS",
    LIFE_GIFTS = "LIFE_GIFTS",
    LIFE_INSURANCES = "LIFE_INSURANCES",
    LIFE_NURSERY = "LIFE_NURSERY",
    LIFE_OTHER = "LIFE_OTHER",
    LIFE_TAXES = "LIFE_TAXES",
    LIFE_UNIVERSITY = "LIFE_UNIVERSITY",
}

export const EXPENSE_TYPES = {
    HOUSE_ELECTRONICS: {
        icon: Zap,
        label: "Electrodomésticos",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_FORNITURE: {
        icon: Armchair,
        label: "Muebles",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_MAINTENANCE: {
        icon: Hammer,
        label: "Mantenimiento",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_MORTGAGE: {
        icon: House,
        label: "Hipoteca",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_OTHER: {
        icon: HousePlus,
        label: "Otros (Casa)",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_PETS: {
        icon: PawPrint,
        label: "Mascotas",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_RENT: {
        icon: House,
        label: "Alquiler",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_SERVICES: {
        icon: HandPlatter,
        label: "Servicios del hogar",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },
    HOUSE_SUPPLIES: {
        icon: Container,
        label: "Suministros",
        color: "transition-colors duration-300 bg-yellow hover:bg-yellow/90",
    },

    FOOD_DRINKS: {
        icon: Beer,
        label: "Bebidas",
        color: "transition-colors duration-300 bg-green hover:bg-green/90",
    },
    FOOD_FOOD: {
        icon: Hamburger,
        label: "Comida",
        color: "transition-colors duration-300 bg-green hover:bg-green/90",
    },
    FOOD_OTHER: {
        icon: CookingPot,
        label: "Otros (Comida)",
        color: "transition-colors duration-300 bg-green hover:bg-green/90",
    },
    FOOD_UTENSILS: {
        icon: Utensils,
        label: "Utensilios",
        color: "transition-colors duration-300 bg-green hover:bg-green/90",
    },

    ENTERTAINMENT_GAMES: {
        icon: Gamepad2,
        label: "Juegos",
        color: "transition-colors duration-300 bg-purple hover:bg-purple/90",
    },
    ENTERTAINMENT_MOVIES: {
        icon: Popcorn,
        label: "Cine y Películas",
        color: "transition-colors duration-300 bg-purple hover:bg-purple/90",
    },
    ENTERTAINMENT_MUSIC: {
        icon: Music,
        label: "Música",
        color: "transition-colors duration-300 bg-purple hover:bg-purple/90",
    },
    ENTERTAINMENT_OTHER: {
        icon: Tickets,
        label: "Otros (Entretenimiento)",
        color: "transition-colors duration-300 bg-purple hover:bg-purple/90",
    },
    ENTERTAINMENT_SPORTS: {
        icon: Volleyball,
        label: "Deportes",
        color: "transition-colors duration-300 bg-purple hover:bg-purple/90",
    },

    UNCATEGORIZED: {
        icon: Receipt,
        label: "Sin categoría",
        color: "transition-colors duration-300 bg-secondary hover:bg-secondary/90",
    },

    TRANSPORT_BUS: {
        icon: BusFront,
        label: "Colectivo",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_CAR: {
        icon: CarFront,
        label: "Auto",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_FUEL: {
        icon: Fuel,
        label: "Combustible",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_HOTEL: {
        icon: Hotel,
        label: "Alojamiento",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_OTHER: {
        icon: Bike,
        label: "Otros (Transporte)",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_PARKING: {
        icon: CircleParking,
        label: "Estacionamiento",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_PLANE: {
        icon: Plane,
        label: "Avión",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_TAXI: {
        icon: CarTaxiFront,
        label: "Taxi",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },
    TRANSPORT_TRAIN: {
        icon: TrainFront,
        label: "Tren",
        color: "transition-colors duration-300 bg-red hover:bg-red/90",
    },

    UTILITIES_CLEANING: {
        icon: BrushCleaning,
        label: "Limpieza",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_HEATING: {
        icon: Heater,
        label: "Calefacción",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_LIGHT: {
        icon: Lightbulb,
        label: "Luz",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_OTHER: {
        icon: NotebookPen,
        label: "Otros (Servicios)",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_PHONE: {
        icon: Phone,
        label: "Teléfono",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_TRASH: {
        icon: Trash2,
        label: "Recolección de residuos",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_TV: {
        icon: Tv,
        label: "Televisión",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_WATTER: {
        icon: Droplet,
        label: "Agua",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },
    UTILITIES_WIFI: {
        icon: Wifi,
        label: "Internet",
        color: "transition-colors duration-300 bg-blue hover:bg-blue/90",
    },

    LIFE_CLOTHES: {
        icon: Shirt,
        label: "Ropa",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_DOCTORS: {
        icon: BriefcaseMedical,
        label: "Gastos médicos",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_GIFTS: {
        icon: Gift,
        label: "Regalos",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_INSURANCES: {
        icon: ShieldCheck,
        label: "Seguros",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_NURSERY: {
        icon: Baby,
        label: "Guardería",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_OTHER: {
        icon: Shell,
        label: "Otros (Vida)",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_TAXES: {
        icon: Calculator,
        label: "Impuestos",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
    LIFE_UNIVERSITY: {
        icon: GraduationCap,
        label: "Universidad",
        color: "transition-colors duration-300 bg-orange hover:bg-orange/90",
    },
};

export const EXPENSE_CATEGORIES = {
    Casa: [
        EXPENSE_TYPE.HOUSE_ELECTRONICS,
        EXPENSE_TYPE.HOUSE_FORNITURE,
        EXPENSE_TYPE.HOUSE_MAINTENANCE,
        EXPENSE_TYPE.HOUSE_MORTGAGE,
        EXPENSE_TYPE.HOUSE_OTHER,
        EXPENSE_TYPE.HOUSE_PETS,
        EXPENSE_TYPE.HOUSE_RENT,
        EXPENSE_TYPE.HOUSE_SERVICES,
        EXPENSE_TYPE.HOUSE_SUPPLIES,
    ],
    Comida: [
        EXPENSE_TYPE.FOOD_DRINKS,
        EXPENSE_TYPE.FOOD_FOOD,
        EXPENSE_TYPE.FOOD_OTHER,
        EXPENSE_TYPE.FOOD_UTENSILS,
    ],
    Entretenimiento: [
        EXPENSE_TYPE.ENTERTAINMENT_GAMES,
        EXPENSE_TYPE.ENTERTAINMENT_MOVIES,
        EXPENSE_TYPE.ENTERTAINMENT_MUSIC,
        EXPENSE_TYPE.ENTERTAINMENT_OTHER,
        EXPENSE_TYPE.ENTERTAINMENT_SPORTS,
    ],
    Transporte: [
        EXPENSE_TYPE.TRANSPORT_BUS,
        EXPENSE_TYPE.TRANSPORT_CAR,
        EXPENSE_TYPE.TRANSPORT_FUEL,
        EXPENSE_TYPE.TRANSPORT_HOTEL,
        EXPENSE_TYPE.TRANSPORT_OTHER,
        EXPENSE_TYPE.TRANSPORT_PARKING,
        EXPENSE_TYPE.TRANSPORT_PLANE,
        EXPENSE_TYPE.TRANSPORT_TAXI,
        EXPENSE_TYPE.TRANSPORT_TRAIN,
    ],
    Servicios: [
        EXPENSE_TYPE.UTILITIES_CLEANING,
        EXPENSE_TYPE.UTILITIES_HEATING,
        EXPENSE_TYPE.UTILITIES_LIGHT,
        EXPENSE_TYPE.UTILITIES_OTHER,
        EXPENSE_TYPE.UTILITIES_PHONE,
        EXPENSE_TYPE.UTILITIES_TRASH,
        EXPENSE_TYPE.UTILITIES_TV,
        EXPENSE_TYPE.UTILITIES_WATTER,
        EXPENSE_TYPE.UTILITIES_WIFI,
    ],
    Vida: [
        EXPENSE_TYPE.LIFE_CLOTHES,
        EXPENSE_TYPE.LIFE_DOCTORS,
        EXPENSE_TYPE.LIFE_GIFTS,
        EXPENSE_TYPE.LIFE_INSURANCES,
        EXPENSE_TYPE.LIFE_NURSERY,
        EXPENSE_TYPE.LIFE_OTHER,
        EXPENSE_TYPE.LIFE_TAXES,
        EXPENSE_TYPE.LIFE_UNIVERSITY,
    ],
    Otro: [EXPENSE_TYPE.UNCATEGORIZED],
} as const;
